#!/bin/bash
# Write a Bash script that redirects the output of the echo command 
# to /dev/null to suppress any output.

echo "This output will be suppressed" > /dev/null

# "> /dev/null" redirects the output of the "echo" command to "/dev/null",
# which is a special file that discards all data written to it. Therefore, any
# output generated by the "echo" command will be suppressed and not
# displayed in the terminal.

